### ISSUE TITLE
万望能够得到您的指导

### ISSUE THREAD

**Issue by originlinyi** [DOUDIU/Canny-Edge-Detection#1]
您好  ，我是西安电子科技大学的学生，方便联系您吗，对于这个工程我有一些疑问  万望能够得到您的指导 1452557493@qq.com

**Comment by DOUDIU** [comment]
您好，我的微信号码：pan15257452037，大家可以一起学习交流一下




℃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DOUDIU/Canny-Edge-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 下午3:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[DOUDIU/Canny-Edge-Detection] 万望能够得到您的指导 (Issue #1)





 
您好  ，我是西安电子科技大学的学生，方便联系您吗，对于这个工程我有一些疑问  万望能够得到您的指导 ***@***.***
