### ISSUE TITLE
关于该工程的一些问题

### ISSUE THREAD

**Issue by xlchenn** [DOUDIU/Canny-Edge-Detection#2]
您好 ，方便联系您吗，对于这个工程我有一些疑问 希望能够得到您的指导 511872150@qq.com
祝好

**Comment by DOUDIU** [comment]
你好！
万分抱歉，早上有事，没有来得及回复，
很开心我的项目能对你起到一定帮助。
如果在工程中有一定的疑惑的话可以直接email个list过来，看到的话会尽量及时回复
指导谈不上，可以就工程问题上相互沟通下


同，祝好！




℃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DOUDIU/Canny-Edge-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午9:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[DOUDIU/Canny-Edge-Detection] 关于该工程的一些问题 (Issue #2)





 
您好 ，方便联系您吗，对于这个工程我有一些疑问 希望能够得到您的指导 ***@***.***
 祝好

**Comment by xlchenn** [comment]
您好！很高兴收到您的回复。
&nbsp; &nbsp; &nbsp; 非常抱歉打扰您了，我想咨询一下您的这个边缘检测项目是否完整呢，因为我看到项目中有提到是用ov5640来采集视频，但是并没有对数据流进行处理的模块，您这个是通过什么总线来处理数据的呢？
因为我是刚入门，所以对整个项目串起来的理解能力比较差。还有我尝试新建vivado工程把代码添加进去，然后通过工程里的ov5640_tb文件来进行仿真，发现数据都是高阻态和不定态。
如果您有未上传的数据，希望您能够分享一下，在此非常感谢。
期待您的回复，祝好！


陈磊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DOUDIU/Canny-Edge-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DOUDIU/Canny-Edge-Detection] 关于该工程的一些问题 (Issue #2)





 你好！ 
 万分抱歉，早上有事，没有来得及回复， 
 很开心我的项目能对你起到一定帮助。 
 如果在工程中有一定的疑惑的话可以直接email个list过来，看到的话会尽量及时回复 
 指导谈不上，可以就工程问题上相互沟通下 
 
 
 同，祝好！ 
 
 
 
 
 ℃ 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "DOUDIU/Canny-Edge-Detection"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年4月11日(星期二) 上午9:55 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[DOUDIU/Canny-Edge-Detection] 关于该工程的一些问题 (Issue #2) 
 
 
 
 
 
   
 您好 ，方便联系您吗，对于这个工程我有一些疑问 希望能够得到您的指导 ***@***.*** 
  祝好

**Comment by DOUDIU** [comment]
你好！
以下是关于对这个项目几个疑问的回复：
Pro1：您的这个边缘检测项目是否完整呢？
Ans1：该项目的仿真工程是比较完整的，tb文件顶层从读取bmp图片数据来模拟OV5640摄像头输出的时序，后续的图像处理模块都是按照通用的接口进行数据处理，并以一个通用的接口信号输出，以方便嵌套各类图像处理模块，所提及的”总线“可以理解成这些通用的接口信号（如de、hs、vs、data信号等）。

Pro2：新建vivado工程仿真后发现数据都是高阻态和不定态，是否有未上传数据
Ans2：tb文件顶层从pic文件夹的bmp图片读取图像数据来模拟OV5640摄像头输出，文件中有一个读取文件的函数用到了相对路径，按照之前设计的逻辑，需将pic文件夹与vivado总工程文件放在同一个目录下，或者尝试使用自己的（相对or绝对）路径替代tb顶层中的路径。

希望这些回答能够起到一定帮助
祝好！

**Comment by xlchenn** [comment]
您好！
感谢您的热心解答，对于仿真的问题，我尝试了修改读取文件路径的方法，使用了绝对路径，但还是无法仿真成功。
根据vivado仿真的提示，说有几个波形的字节太大，超出了限制，需要在控制台修改。
我怀疑可能是这个原因导致的，我在网上搜索了此类问题并没有相关的解答。
附件里有相关截图，请问我该如何解决这个问题呢。
期待您的回复。
祝好！




陈磊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DOUDIU/Canny-Edge-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 晚上6:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DOUDIU/Canny-Edge-Detection] 关于该工程的一些问题 (Issue #2)





 
你好！
 以下是关于对这个项目几个疑问的回复：
 Pro1：您的这个边缘检测项目是否完整呢？
 Ans1：该项目的仿真工程是比较完整的，tb文件顶层从读取bmp图片数据来模拟OV5640摄像头输出的时序，后续的图像处理模块都是按照通用的接口进行数据处理，并以一个通用的接口信号输出，以方便嵌套各类图像处理模块，所提及的”总线“可以理解成这些通用的接口信号（如de、hs、vs、data信号等）。
 
Pro2：新建vivado工程仿真后发现数据都是高阻态和不定态，是否有未上传数据
 Ans2：tb文件顶层从pic文件夹的bmp图片读取图像数据来模拟OV5640摄像头输出，文件中有一个读取文件的函数用到了相对路径，按照之前设计的逻辑，需将pic文件夹与vivado总工程文件放在同一个目录下，或者尝试使用自己的（相对or绝对）路径替代tb顶层中的路径。
 
希望这些回答能够起到一定帮助
 祝好！

**Comment by DOUDIU** [comment]
您好！
  非常抱歉，今天我又重新检查了我的工程，本地可以正常运行vivado仿真，但用modelsim仿真时发现工程似乎有点问题，包括bmp图片格式，部分源码文件在其他目录等。
  现已更新新的版本的工程文件及modelsim仿真工程，注意查看readme文件。
  希望这次上传的文件能够起到一定帮助。
祝好！
